/**
* Jenkins file to deploy and restart Kokoro API service on the host nodes.
* 
* Pipeline URL: <add here>
*/

pipeline {
  agent any
  parameters {
    string(
      name: 'IMAGE_VERSION',
      defaultValue: '0.1.0',
      description: 'Docker image tag to build and deploy'
    )
  }
  stages {
    stage('Install uv') {
        steps {
            sh '''
                sh 'curl -LsSf https://astral.sh/uv/install.sh | sh'
                uv venv --python 3.10
                uv sync --extra cpu --no-cache --no-install-project
            '''
        }
    }
    stage('Test') {
        steps {
            sh '''
                set -euo pipefail
                uv run --extra test --extra cpu pytest api/tests/ --asyncio-mode=auto --cov=api --cov-report=term-missing
            '''
        }
    }
    // stage('Build') {
    //     steps {
    //         sh '''
    //             set -euo pipefail
    //             IMAGE_TAG="bgmp-kokoro-tts:${IMAGE_VERSION}"
    //             docker compose -f docker/cpu/docker-compose.yml build
    //             IMAGE_ID="$(docker compose -f docker/cpu/docker-compose.yml images -q kokoro-tts)"
    //             docker tag "${IMAGE_ID}" "${IMAGE_TAG}"
    //         '''
    //     }
    // }
    // stage('Push') {
    //     steps {
    //         sh '''
    //             set -euo pipefail
    //             IMAGE_TAG="bgmp-kokoro-tts:${IMAGE_VERSION}"
    //             docker push "${IMAGE_TAG}"
    //         '''
    //     }
    // }
    // stage('Deploy') {
    //   steps {
    //     sh '''
    //       NODES=() # TODO: Add nodes once servers are wired up
    //       docker save "${IMAGE_TAG}" -o "/tmp/bgmp-kokoro-tts-${IMAGE_VERSION}.tar"
    //       for NODE in "${NODES[@]}"; do
    //         scp "/tmp/bgmp-kokoro-tts-${IMAGE_VERSION}.tar" "${NODE}:/tmp/"
    //         rsync -av "${SERVICE_FILE}" "${NODE}:/etc/systemd/system/kokoro-tts.service"
    //         ssh ${NODE} "docker load -i /tmp/bgmp-kokoro-tts-${IMAGE_VERSION}.tar && systemctl daemon-reload && systemctl restart kokoro-tts"
    //       done
    //     '''
    //   }
    // }
  }
}
