/**
* Jenkins file to deploy and restart Kokoro API service on the host nodes.
* 
* Pipeline URL: https://jenkins.boston.com/dev2/job/bgmp-kokoro-fastapi-build-push/
*/

pipeline {
  agent {
			label 'docker'
		}
  parameters {
    string(
      name: 'IMAGE_NAME',
      defaultValue: 'bgmp-kokoro-tts',
      description: 'Docker image name to build and push'
    )
    string(
      name: 'IMAGE_VERSION',
      defaultValue: '0.1.0',
      description: 'Docker image tag to build and push'
    )
    booleanParam(
      name: 'DRY_RUN',
      defaultValue: true,
      description: 'If unchecked, will push image to GHCR. Else it will just build and test.'
    )
  }
  environment {
    GITHUB_PAT=credentials('bgmp-kokoro-fastapi')
  }
  stages {
    stage('Prepare Environment') {
      steps {
          script {
              // Get the current user and group IDs.
              userId = sh(
                  script: 'id -u',
                  returnStdout: true
              ).trim()
              groupId = sh(
                  script: 'id -g',
                  returnStdout: true
              ).trim()

              // Check if Docker is running
              def isDockerRunning = sh(
                  script: "dzdo systemctl is-active docker",
                  returnStatus: true
              ) == 0

              if (isDockerRunning) {
                  // Change permissions if Docker is running
                  sh "dzdo chown root:docker /var/run/docker.sock"
              } else {
                  // Restart Docker if it is not running
                  echo "Docker is not running. Restarting Docker service."
                  sh "dzdo systemctl restart docker"
                  // Wait a moment for Docker to start
                  sleep(time: 10, unit: 'SECONDS')
                  // Then change permissions
                  sh "dzdo chown root:docker /var/run/docker.sock"
              }
          }
      }
    }
    stage('Login to GHCR') {
      steps {
        script{
          if(params.DRY_RUN){
            echo "Dry run only, not logging in to GHCR"
          }else{
            sh 'echo $GITHUB_PAT_PSW | docker login ghcr.io -u $GITHUB_PAT_USR --password-stdin'
          }
        }
      }
    }
    stage('Validate Image Tag'){
        steps {
            script {
              if(params.DRY_RUN){
                echo "Dry run only, image tag not relevant, skipping check"
              }else{ 
                def remoteImageTag = "ghcr.io/bostonglobe/${params.IMAGE_NAME}:${params.IMAGE_VERSION}"
                def imageExists = sh(
                  script: "docker manifest inspect ${remoteImageTag} >/dev/null 2>&1",
                  returnStatus: true
                ) == 0

                if (imageExists) {
                  error("Image tag already exists in registry: ${remoteImageTag}")
                }else{
                  echo "Image tag does not yet exist, tagging image..."
                }
              }
            }
        }      
    }
    stage('Test') {
      steps {
        script {
          def imageTag = "${params.IMAGE_NAME}:${params.IMAGE_VERSION}"
          def buildArgs = [
            '--build-arg INCLUDE_JAPANESE=false',
            '--target unit-test'
          ].join(' ')

          docker.build(
            imageTag,
            "${buildArgs} -f docker/cpu/Dockerfile.optimized ."
          )
        }
      }
    }
    stage('Build') {
      steps {
        script {
          def imageTag = "${params.IMAGE_NAME}:${params.IMAGE_VERSION}"
          def buildArgs = [
            '--build-arg INCLUDE_JAPANESE=false',
            '--no-cache'
          ].join(' ')

          docker.build(
            imageTag,
            "${buildArgs} -f docker/cpu/Dockerfile.optimized ."
          )

          echo "Built Docker image ${imageTag}"
        }
      }
    }
    stage('Push') {
        steps {
            script {

              if(params.DRY_RUN){
                echo "Dry run only, skipping push step."
              }else{
                def localImageTag = "${params.IMAGE_NAME}:${params.IMAGE_VERSION}"
                def remoteImageTag = "ghcr.io/bostonglobe/${params.IMAGE_NAME}:${params.IMAGE_VERSION}"
                sh "docker tag ${localImageTag} ${remoteImageTag}"
                sh "docker push ${remoteImageTag}"
              }
            }
        }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }
}
