/**
* Jenkins file to run load tests on the Kokoro API service in QA.
* 
* Pipeline URL: <TODO>
*/

pipeline{
    agent {
			label 'docker'
		}
    parameters {
        choice (
            name: 'TEST_TYPE',
            choices: ['baseline'],
            description: 'Type of load test to run'
        )
    }
    stages {
        stage('Prepare Environment') {
            steps {
                script {
                    // Get the current user and group IDs.
                    userId = sh(
                        script: 'id -u',
                        returnStdout: true
                    ).trim()
                    groupId = sh(
                        script: 'id -g',
                        returnStdout: true
                    ).trim()

                    // Check if Docker is running
                    def isDockerRunning = sh(
                        script: "dzdo systemctl is-active docker",
                        returnStatus: true
                    ) == 0

                    if (isDockerRunning) {
                        // Change permissions if Docker is running
                        sh "dzdo chown root:docker /var/run/docker.sock"
                    } else {
                        // Restart Docker if it is not running
                        echo "Docker is not running. Restarting Docker service."
                        sh "dzdo systemctl restart docker"
                        // Wait a moment for Docker to start
                        sleep(time: 10, unit: 'SECONDS')
                        // Then change permissions
                        sh "dzdo chown root:docker /var/run/docker.sock"
                    }
                }
            }
        }
        stage('Checkout git repo') {
            steps {
                checkout scm
            }
        }
        stage('Baseline Load Test') {
            steps {
                script {
                    sh 'cd tests'
                    sh 'ls'
                    def imageTag = "${params.TEST_TYPE}-load-test"

                    sh "docker build -t ${imageTag} tests"

                    echo "Built Docker image ${imageTag}"
                    sh "docker run ${imageTag}"
                    sh "docker rmi --force ${imageTag}"
                }
            }
        }
    }
}