/**
* Jenkins file to run load tests on the Kokoro API service in QA.
* 
* Pipeline URL: <TODO>
*/

pipeline{
    agent {
			label 'docker'
		}
    parameters {
        choice (
            name: 'TEST_TYPE',
            choices: ['baseline'],
            description: 'Type of load test to run'
        )
    }
    stages {
        stage('Checkout git repo') {
            steps {
                checkout scm
                sh 'cd tests'
            }
        }
        stage('Load Test') {
            steps {
                script {
                def imageTag = "${params.TEST_TYPE}-load-test"

                docker.build(
                    imageTag
                )

                echo "Built Docker image ${imageTag}"
                }
                sh "docker run ${imageTag}"
                sh "docker rmi ${imageTag}"
            }
        }
    }
}