/**
* Jenkins file to run load tests on the Kokoro API service in QA.
* 
* Pipeline URL: <TODO>
*/

pipeline{
    agent any
    parameters {
        choice (
            name: 'TEST_TYPE',
            choices: ['baseline'],
            description: 'Type of load test to run'
        )
    }
    stages {
        stage('Checkout git repo') {
            steps {
                checkout scm
                sh 'dzdo apt update -y'
                sh 'dzdo apt install siege -y'
            }
        }
        stage('Run Baseline Test'){
            steps {
                sh '''
                    cd tests
                    ./siege_baseline.sh
                '''
            }
        }
    }
    post {
        always {
            sh 'dzdo apt remove siege -y'
        }
    }
}